//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1Up_Mushroom {
            get {
                object obj = ResourceManager.GetObject("_1Up_Mushroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_1hp {
            get {
                object obj = ResourceManager.GetObject("Brick_1hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_2hp {
            get {
                object obj = ResourceManager.GetObject("Brick_2hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_3hp {
            get {
                object obj = ResourceManager.GetObject("Brick_3hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_4hp {
            get {
                object obj = ResourceManager.GetObject("Brick_4hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_5hp {
            get {
                object obj = ResourceManager.GetObject("Brick_5hp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brick_Question {
            get {
                object obj = ResourceManager.GetObject("Brick_Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dababyBackground {
            get {
                object obj = ResourceManager.GetObject("dababyBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Double_Cherry {
            get {
                object obj = ResourceManager.GetObject("Double_Cherry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fire {
            get {
                object obj = ResourceManager.GetObject("fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fire_Flower {
            get {
                object obj = ResourceManager.GetObject("Fire_Flower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Score&gt;
        ///  
        ///&lt;/Score&gt;
        ///.
        /// </summary>
        internal static string highscores {
            get {
                return ResourceManager.GetString("highscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap howtoplay {
            get {
                object obj = ResourceManager.GetObject("howtoplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LebronBackground {
            get {
                object obj = ResourceManager.GetObject("LebronBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LebronJames {
            get {
                object obj = ResourceManager.GetObject("LebronJames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;25&lt;/x&gt;
        ///    &lt;y&gt;162&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;4&lt;/colour&gt;
        ///    &lt;type&gt;0&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;56&lt;/x&gt;
        ///    &lt;y&gt;153&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;4&lt;/colour&gt;
        ///    &lt;type&gt;0&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;87&lt;/x&gt;
        ///    &lt;y&gt;144&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;4&lt;/colour&gt;
        ///    &lt;type&gt;0&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;118&lt;/x&gt;
        ///    &lt;y&gt;135&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;4&lt;/colour&gt;
        ///    &lt;type&gt;0&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;92&lt;/x&gt;
        ///    &lt;y&gt;83&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;92&lt;/x&gt;
        ///    &lt;y&gt;117&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;92&lt;/x&gt;
        ///    &lt;y&gt;153&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;132&lt;/x&gt;
        ///    &lt;y&gt;153&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;16&lt;/x&gt;
        ///    &lt;y&gt;7&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;70&lt;/x&gt;
        ///    &lt;y&gt;32&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;126&lt;/x&gt;
        ///    &lt;y&gt;57&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;182&lt;/x&gt;
        ///    &lt;y&gt;79&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;colour&gt;1&lt;/colour&gt;
        ///    &lt;type&gt;1&lt;/type&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainbackground {
            get {
                object obj = ResourceManager.GetObject("mainbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarioBackground {
            get {
                object obj = ResourceManager.GetObject("MarioBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarioStand {
            get {
                object obj = ResourceManager.GetObject("MarioStand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mini_Mushroom {
            get {
                object obj = ResourceManager.GetObject("Mini_Mushroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream New_Super_Mario_Bros__Wii___Mini_Mushroom_Sound_Effect {
            get {
                return ResourceManager.GetStream("New_Super_Mario_Bros__Wii___Mini_Mushroom_Sound_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rainbow_effect2 {
            get {
                object obj = ResourceManager.GetObject("rainbow_effect2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap realbubble {
            get {
                object obj = ResourceManager.GetObject("realbubble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Super_Mario_Bros____1_UP_Mushroom_Sound_Effect {
            get {
                return ResourceManager.GetStream("Super_Mario_Bros____1_UP_Mushroom_Sound_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Super_Mario_Bros____Mushroom_Sound_Effect {
            get {
                return ResourceManager.GetStream("Super_Mario_Bros____Mushroom_Sound_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Super_Mario_Land_PowerUp_Sound_Effect__Free_Ringtone_Download_ {
            get {
                return ResourceManager.GetStream("Super_Mario_Land_PowerUp_Sound_Effect__Free_Ringtone_Download_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Super_Mario_Star_Sound {
            get {
                return ResourceManager.GetStream("Super_Mario_Star_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Super_Mushroom {
            get {
                object obj = ResourceManager.GetObject("Super_Mushroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Super_Star {
            get {
                object obj = ResourceManager.GetObject("Super_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
